# -*- coding: utf-8 -*-
"""user_input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNS_cs7M_xejGuMDkZtvbc-n0uyFSiZl
"""

ProjectName = str(input("Enter Project Name: "))
labour = float(input("Hourly labour cost in USD? "))
travel = float(input("Travel time to device? (in hours) "))
task = float(input("How long does it take to take a reading? (in hours) "))
cadence = int(input("How many times a month do you go to site? "))

costpermsg = float(input("Cost per message in USD? "))
msgperday = int(input("How many readings per day? "))


costpervisit = ((travel*2)+task)*labour
costperyear = (costpervisit*cadence)*12
myriotacostday = costpermsg*msgperday
myriotacostmonth = myriotacostday*30

savingsmonth = (costpervisit*cadence)-myriotacostmonth
savingsyr = savingsmonth*12


print("Project Name is:", ProjectName)
print("Hourly cost of labour is: $",labour,"USD")
print("Travel time to and from site is:",(travel*2),"hours")
print("Time on site taking a reading is:",task,"hours")

print("Your Myriota cost per tank reading is:",costpermsg,"USD")
print("You will be getting:",msgperday,"tank level readings per day")

print("You will save",savingsyr,"USD per year")